pipeline {
    agent any

    tools {
        terraform 'terraform' 
    }
    environment {
        // Terraform leerá estas variables de entorno de forma automática
        TF_VAR_aws_access_key = credentials('AWS-ACCESS-KEY-ID')
        TF_VAR_aws_secret_key = credentials('AWS-SECRET-ACCESS-KEY')
        TF_VAR_aws_endpoint_url = "${env.AWS_ENDPOINT_URL}"
        TF_VAR_aws_region = "us-east-1"
        REPO_URL = "https://github.com/ragnarok21/aws-jenkins-terraform-example.git"
        BRANCH = "master"
        CREDENTIALS_ID = "GITHUB_CREDENTIALS"
    }
    
    stages {
        stage('Checkout Repo Terraform file') {
            steps {
                script {
                    def credentialsId = env.CREDENTIALS_ID?.trim()
                    if (!credentialsId) {
                        error('Debes indicar un CREDENTIALS_ID existente en Jenkins')
                    }

                    // Descarga explícita del repositorio usando credenciales existentes en Jenkins
                    checkout scmGit(
                        branches: [[name: env.BRANCH]],
                        userRemoteConfigs: [[
                            url: env.REPO_URL,
                            credentialsId: credentialsId
                        ]]
                    )
                }
            }
        }

        stage('Get Terraform File Name') {
            steps {
                script {
                    dir('terraform-templates') {
                        // Obtiene el nombre del archivo .tf
                        def tfFileName = sh(script: 'ls -1 *.tf | head -1', returnStdout: true).trim()
                        if (tfFileName) {
                            echo "Archivo Terraform encontrado: ${tfFileName}"
                            env.TF_FILE_NAME = tfFileName
                        } else {
                            error('No se encontraron archivos .tf en terraform-templates')
                        }
                    }
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform-templates') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    dir('terraform-templates') {
                        // Usa el nombre del archivo .tf para generar el nombre del plan
                        def planName = env.TF_FILE_NAME.replaceAll(/\.tf$/, '.tfplan')
                        sh "terraform plan -out=${planName}"
                        env.TFPLAN_NAME = planName
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform-templates') {
                    sh "terraform apply -auto-approve ${env.TFPLAN_NAME}"
                }
            }
        }
    }
}
